"""Case Scaffolder — create standard Framepack video case directory structure.

When Framepack starts a new video case inside a workbench, this module
creates the standard directory layout (cases/<slug>/) with HyperFrames
project files, case-level AGENTS.md managed block, .framepack/ evidence
directory, and .hyperframes/ directory.

This is deterministic: it doesn't rely on the Agent remembering folder
hygiene.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional

from hooks.guardrails import build_guardrails_payload, build_managed_block


class CaseClass(str, Enum):
    STANDARD_CASE = "standard_case"
    LEGACY_CASE = "legacy_case"
    RESEARCH_CASE = "research_case"
    RENDERABLE_DRAFT = "renderable_draft"
    EMPTY = "empty"


@dataclass(frozen=True)
class ScaffoldResult:
    """Result of scaffolding a new case."""
    case_dir: str
    action: str  # "created" | "exists" | "error"
    files_created: list[str] = field(default_factory=list)
    dirs_created: list[str] = field(default_factory=list)
    error: Optional[str] = None


@dataclass(frozen=True)
class CaseClassification:
    """Classification of an existing case directory."""
    case_dir: str
    label: CaseClass
    has_agents: bool
    has_claude: bool
    has_hyperframes_json: bool
    has_package_json: bool
    has_frame_md: bool
    has_expanded_prompt: bool
    has_index_html: bool
    has_framepack_dir: bool
    notes: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Standard file/directory layout
# ---------------------------------------------------------------------------

STANDARD_DIRS = [
    ".framepack",
    ".hyperframes",
    "assets",
    "renders",
]

STANDARD_FRAMEPACK_ARTIFACTS = [
    "asset-intake.md",
    "director-inspect.md",
    "script-lanes.md",
    "handoff-manifest.md",
    "arsenal.json",
    "catalog-decision.md",
    "studio-preview.md",
    "render-readiness.md",
    "taste-audit.md",
]

PLACEHOLDER_BODY = {
    "asset-intake.md": "# Asset Intake\n\n## Brand\n- logo:\n- colors:\n- fonts:\n\n## Products\n\n## Missing\n",
    "director-inspect.md": "# Director Inspect\n\n## 9-question rubric\n1. Who is this for?\n2. What must the first second make them feel?\n3. What is the story turn?\n4. What proof makes it believable?\n5. What assets are available?\n6. What assets are missing?\n7. Is music background, spine, or optional?\n8. What must never appear?\n9. What does success look like?\n\n## User decision\n- (pending)\n",
    "script-lanes.md": "# Script Lanes\n\n## Lane A\n- hook:\n- beats:\n- final line:\n\n## Lane B\n- hook:\n- beats:\n- final line:\n\n## Selected lane\n- lane:\n- user_confirmed: false\n",
    "handoff-manifest.md": "# Handoff Manifest\n\n- workflow:\n- source_inputs:\n- creative_constraints:\n- catalog_candidates:\n- arsenal_candidates:\n- qa_redlines:\n",
    "arsenal.json": '{\n  "weapons": {}\n}\n',
    "catalog-decision.md": "# HyperFrames Catalog Decision\n\n## Case needs\n\n## Candidates evaluated\n| candidate | use? | reason |\n|---|---|---|\n\n## Decision\n- used_components:\n- waived_components:\n",
    "studio-preview.md": "# Studio Preview Evidence\n\n- command:\n- started_at:\n- inspection_method:\n\n## Observations\n\n## Waiver\n- skipped: false\n- reason:\n",
    "render-readiness.md": "# Render Readiness Board\n\n(generated by framepack_readiness)\n",
    "taste-audit.md": "# Pre-render Taste Audit\n\n(audit pending)\n",
}


def scaffold_case(
    workbench_root: Path | str,
    case_slug: str,
    plugin_dir: Path | str,
    hyperframes_version: str = "0.7.21",
    create_claude_md: bool = False,
) -> ScaffoldResult:
    """Create a standard Framepack video case directory.

    Args:
        workbench_root: Path to the workbench root (has WORKBENCH.md / cases/)
        case_slug: Case directory name, e.g. "ederson-manutd-30s"
        plugin_dir: Path to the deployed plugin (for guardrails payload)
        hyperframes_version: Pin version in package.json
        create_claude_md: Also create CLAUDE.md mirror
    """
    workbench_root = Path(workbench_root)
    case_dir = workbench_root / "cases" / case_slug

    if case_dir.exists() and any(case_dir.iterdir()):
        return ScaffoldResult(
            case_dir=str(case_dir),
            action="exists",
            error="case directory already exists and is non-empty",
        )

    files_created: list[str] = []
    dirs_created: list[str] = []

    # Directories
    for d in STANDARD_DIRS:
        target = case_dir / d
        target.mkdir(parents=True, exist_ok=True)
        dirs_created.append(d)

    # Case AGENTS.md managed block
    payload = build_guardrails_payload(Path(plugin_dir))
    agents_content = (
        f"# {case_slug}\n\n"
        f"This is a Framepack video case.\n\n"
        + payload.block
    )
    (case_dir / "AGENTS.md").write_text(agents_content, encoding="utf-8", newline="\n")
    files_created.append("AGENTS.md")

    if create_claude_md:
        (case_dir / "CLAUDE.md").write_text(agents_content, encoding="utf-8", newline="\n")
        files_created.append("CLAUDE.md")

    # HyperFrames project files
    package_json = {
        "name": case_slug,
        "version": "1.0.0",
        "private": True,
        "scripts": {
            "lint": f"npx hyperframes@{hyperframes_version} lint",
            "validate": f"npx hyperframes@{hyperframes_version} validate",
            "inspect": f"npx hyperframes@{hyperframes_version} inspect",
            "preview": f"npx hyperframes@{hyperframes_version} preview",
            "render": f"npx hyperframes@{hyperframes_version} render",
        },
    }
    import json
    (case_dir / "package.json").write_text(
        json.dumps(package_json, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    files_created.append("package.json")

    (case_dir / "hyperframes.json").write_text(
        json.dumps({"version": hyperframes_version, "composition": "index.html"}, indent=2) + "\n",
        encoding="utf-8", newline="\n",
    )
    files_created.append("hyperframes.json")

    # frame.md placeholder
    (case_dir / "frame.md").write_text(
        "# Visual Identity\n\n## Colors\n## Typography\n## Motion\n",
        encoding="utf-8", newline="\n",
    )
    files_created.append("frame.md")

    # .hyperframes/expanded-prompt.md placeholder
    (case_dir / ".hyperframes" / "expanded-prompt.md").write_text(
        "# Director Story Bible\n\n(creative direction pending)\n",
        encoding="utf-8", newline="\n",
    )
    files_created.append(".hyperframes/expanded-prompt.md")

    # .framepack/ artifact placeholders
    for artifact in STANDARD_FRAMEPACK_ARTIFACTS:
        body = PLACEHOLDER_BODY.get(artifact, f"# {artifact.replace('-', ' ').title()}\n\n(pending)\n")
        (case_dir / ".framepack" / artifact).write_text(
            body, encoding="utf-8", newline="\n"
        )
        files_created.append(f".framepack/{artifact}")

    return ScaffoldResult(
        case_dir=str(case_dir),
        action="created",
        files_created=files_created,
        dirs_created=dirs_created,
    )


# ---------------------------------------------------------------------------
# Case classification
# ---------------------------------------------------------------------------

def classify_case(case_dir: Path | str) -> CaseClassification:
    """Classify an existing case directory by its completeness."""
    case_dir = Path(case_dir)

    def _has(name: str) -> bool:
        return (case_dir / name).exists()

    def _has_fp(name: str) -> bool:
        return (case_dir / ".framepack" / name).exists()

    has_agents = _has("AGENTS.md")
    has_claude = _has("CLAUDE.md")
    has_hf_json = _has("hyperframes.json")
    has_pkg = _has("package.json")
    has_frame = _has("frame.md")
    has_expanded = _has(".hyperframes/expanded-prompt.md")
    has_index = _has("index.html")
    has_fp_dir = (case_dir / ".framepack").is_dir()

    notes: list[str] = []

    # Empty
    if not any(child.is_file() for child in case_dir.iterdir() if child.exists()):
        label = CaseClass.EMPTY
    # Research case: only has index.html or research files, no frame.md
    elif not has_frame and not has_expanded:
        label = CaseClass.RESEARCH_CASE
        notes.append("no frame.md or expanded-prompt.md; likely not a standard video case")
    # Standard case: has the full scaffold
    elif has_frame and has_expanded and has_hf_json and has_pkg and has_agents:
        if has_fp_dir:
            label = CaseClass.STANDARD_CASE
        else:
            label = CaseClass.STANDARD_CASE
            notes.append("has project files but no .framepack/ directory")
    # Renderable draft: can render but lacks workflow evidence
    elif has_index and has_frame:
        label = CaseClass.RENDERABLE_DRAFT
        notes.append("can render but missing workflow evidence (.framepack/ artifacts)")
    # Legacy: has some files but incomplete
    else:
        label = CaseClass.LEGACY_CASE
        if not has_agents:
            notes.append("missing AGENTS.md")
        if not has_hf_json:
            notes.append("missing hyperframes.json")
        if not has_pkg:
            notes.append("missing package.json")

    return CaseClassification(
        case_dir=str(case_dir),
        label=label,
        has_agents=has_agents,
        has_claude=has_claude,
        has_hyperframes_json=has_hf_json,
        has_package_json=has_pkg,
        has_frame_md=has_frame,
        has_expanded_prompt=has_expanded,
        has_index_html=has_index,
        has_framepack_dir=has_fp_dir,
        notes=notes,
    )
