"""Context Hydrator — workbench-wide AGENTS.md/CLAUDE.md version sync.

Extends the existing Guardrail Hydrator pattern: instead of only syncing
the current project's AGENTS.md managed block, this module scans an
entire workbench (root + cases/*) for stale instruction files and
generates a context-sync.md report.

This solves the problem where test workbench files like
F:/Framepack-01-test/AGENTS.md still say "version: 0.11.0" while the
deployed plugin is v0.17.0.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from hooks.guardrails import (
    BLOCK_RE,
    build_guardrails_payload,
    sync_project_agents,
    _managed_block_matches,
    GuardrailsPayload,
    GuardrailsSyncResult,
)


@dataclass(frozen=True)
class ContextFileStatus:
    """Status of one instruction file (AGENTS.md or CLAUDE.md)."""
    path: str
    exists: bool
    has_managed_block: bool
    detected_version: str  # from managed block, or "none" / "unknown"
    is_stale: bool
    action_needed: str  # "none" | "create" | "update_block" | "append_block"


@dataclass(frozen=True)
class ContextSyncReport:
    """Full report of a context sync scan."""
    workbench_root: str
    plugin_version: str
    plugin_digest: str
    files: list[ContextFileStatus]
    project_context_current: bool
    stale_files: list[str] = field(default_factory=list)
    error: Optional[str] = None


def _detect_managed_version(text: str) -> str:
    """Extract version from a FRAMEPACK MANAGED BLOCK if present."""
    match = BLOCK_RE.search(text)
    if not match:
        return "none"
    block = match.group(0)
    version_match = re.search(r"version=([^\s]+)", block)
    return version_match.group(1) if version_match else "unknown"


def _detect_old_framepack_version(text: str) -> str:
    """Detect version from old-style full-copy AGENTS.md (pre-managed-block)."""
    match = re.search(r"version:\s*([\d.]+)", text, re.IGNORECASE)
    return match.group(1) if match else "unknown"


# Patterns that indicate old Framepack positioning in file body
_STALE_BODY_PATTERNS = [
    re.compile(r"version:\s*0\.(?:[0-9]|1[0-3])\.", re.IGNORECASE),  # 0.0.x — 0.13.x
    re.compile(r"Prompt Factory", re.IGNORECASE),
    re.compile(r"创意引擎", re.IGNORECASE),
    re.compile(r"Phase 1:\s*意图翻译", re.IGNORECASE),
]


def _has_stale_body(text: str, block_match: re.Match | None) -> tuple[bool, str]:
    """Check if the file body (outside managed block) has stale Framepack content.

    Returns (is_stale, reason).
    """
    if block_match is None:
        body = text
    else:
        body = text[:block_match.start()] + text[block_match.end():]

    for pat in _STALE_BODY_PATTERNS:
        m = pat.search(body)
        if m:
            return True, f"stale body pattern: {m.group(0)}"
    return False, ""


def _check_one_file(
    file_path: Path,
    plugin_payload: GuardrailsPayload,
) -> ContextFileStatus:
    """Check a single context file (AGENTS.md / CLAUDE.md / WORKBENCH.md)."""
    if not file_path.exists():
        return ContextFileStatus(
            path=str(file_path),
            exists=False,
            has_managed_block=False,
            detected_version="none",
            is_stale=False,
            action_needed="none",
        )

    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ContextFileStatus(
            path=str(file_path),
            exists=True,
            has_managed_block=False,
            detected_version="read_error",
            is_stale=True,
            action_needed="none",
        )

    block_match = BLOCK_RE.search(text)
    has_block = block_match is not None
    detected = _detect_managed_version(text) if has_block else _detect_old_framepack_version(text)

    # Check for stale body content even if managed block is current
    stale_body, stale_reason = _has_stale_body(text, block_match)

    # WORKBENCH.md is a user document, not an instruction file.
    # Only flag it if it contains stale Framepack guide content.
    is_workbench = file_path.name == "WORKBENCH.md"

    # CLAUDE.md generated by HyperFrames (not Framepack) should not be
    # forced to have a Framepack managed block. Only flag if stale body.
    is_hyperframes_claude = (
        file_path.name == "CLAUDE.md"
        and "HyperFrames Composition Project" in text[:500]
    )

    if is_workbench or is_hyperframes_claude:
        # For these files, only stale body matters, not missing managed block
        version_stale = False
        block_stale = False
        is_stale = stale_body
    else:
        # For AGENTS.md / Framepack-created CLAUDE.md, both version, block digest,
        # and stale body matter. Version-only checks miss same-version guardrail
        # updates (for example v0.17.0 Template Menu First landing after release).
        version_stale = detected != plugin_payload.version
        block_stale = bool(has_block and block_match and not _managed_block_matches(block_match, plugin_payload))
        is_stale = version_stale or block_stale or stale_body

    if stale_body and (not version_stale or is_workbench or is_hyperframes_claude):
        action = "replace_stale_body"
    elif not has_block and not is_workbench and not is_hyperframes_claude:
        action = "append_block"
    elif version_stale or block_stale:
        action = "update_block"
    else:
        action = "none"

    return ContextFileStatus(
        path=str(file_path),
        exists=True,
        has_managed_block=has_block,
        detected_version=detected,
        is_stale=is_stale,
        action_needed=action,
    )


def find_workbench_root(project_dir: Path | str) -> Optional[Path]:
    """Walk up from project_dir to find the workbench root.

    A workbench root is identified by having WORKBENCH.md or
    (AGENTS.md + cases/ directory).
    """
    current = Path(project_dir).resolve()
    for candidate in [current] + list(current.parents):
        if (candidate / "WORKBENCH.md").is_file():
            return candidate
        if (candidate / "cases").is_dir() and (candidate / "AGENTS.md").is_file():
            return candidate
    return None


def collect_context_files(workbench_root: Path) -> list[Path]:
    """Collect all context files in a workbench.

    Scans AGENTS.md, CLAUDE.md, and WORKBENCH.md at root + case level.
    """
    targets: list[Path] = []

    # Root level
    for name in ("AGENTS.md", "CLAUDE.md", "WORKBENCH.md"):
        p = workbench_root / name
        targets.append(p)

    # Case level
    cases_dir = workbench_root / "cases"
    if cases_dir.is_dir():
        for case in sorted(cases_dir.iterdir()):
            if not case.is_dir():
                continue
            for name in ("AGENTS.md", "CLAUDE.md"):
                p = case / name
                targets.append(p)

    return targets


def check_context_sync(
    workbench_root: Path | str,
    plugin_dir: Path | str,
) -> ContextSyncReport:
    """Scan a workbench for stale context files. Read-only; does not write."""
    workbench_root = Path(workbench_root)
    plugin_dir = Path(plugin_dir)

    payload = build_guardrails_payload(plugin_dir)
    targets = collect_context_files(workbench_root)

    file_statuses: list[ContextFileStatus] = []
    stale: list[str] = []

    for target in targets:
        status = _check_one_file(target, payload)
        file_statuses.append(status)
        if status.is_stale and status.exists:
            stale.append(f"{status.path} (detected: {status.detected_version})")

    project_current = len(stale) == 0

    return ContextSyncReport(
        workbench_root=str(workbench_root),
        plugin_version=payload.version,
        plugin_digest=payload.digest,
        files=file_statuses,
        project_context_current=project_current,
        stale_files=stale,
    )


def _strip_stale_body(file_path: Path) -> bool:
    """Remove old Framepack full-copy body from a file, keeping only user
    content and the managed block.

    Old AGENTS.md files (pre-managed-block) contain the ENTIRE Framepack
    guide as regular text. This function detects the guide start marker
    (# Framepack Agent Guide) and removes everything from there to the
    managed block, preserving any user content above the guide and the
    managed block itself.

    Returns True if file was rewritten.
    """
    text = file_path.read_text(encoding="utf-8", errors="replace")
    block_match = BLOCK_RE.search(text)

    # Find the old guide start
    guide_start = text.find("# Framepack Agent Guide")
    if guide_start == -1:
        return False  # No old guide marker — nothing to strip

    # User content is everything BEFORE the old guide
    user_content = text[:guide_start].strip()

    # Managed block (if present) is kept as-is
    if block_match:
        new_text = user_content + "\n\n" + block_match.group(0).strip() + "\n"
    else:
        new_text = user_content + "\n"

    if new_text.strip() == text.strip():
        return False

    file_path.write_text(new_text, encoding="utf-8", newline="\n")
    return True


def ensure_workbench_root_agents(
    project_dir: Path | str,
    plugin_dir: Path | str,
    ctx=None,
    reason: str = "workbench root context",
) -> Optional[GuardrailsSyncResult]:
    """Ensure the workbench root AGENTS.md has the current Framepack block.

    This is intentionally narrower than hydrate_context(): it does not scan or
    report the whole workbench and it does not touch WORKBENCH.md/CLAUDE.md.
    It only creates or updates the FRAMEPACK MANAGED BLOCK in the workbench
    root AGENTS.md, preserving all user content outside that block.
    """
    workbench_root = find_workbench_root(project_dir)
    if workbench_root is None:
        return None
    return sync_project_agents(workbench_root, plugin_dir, ctx=ctx, reason=reason)


def _case_dirs_with_context_files(workbench_root: Path) -> list[Path]:
    cases_dir = workbench_root / "cases"
    if not cases_dir.is_dir():
        return []
    result: list[Path] = []
    for case_dir in sorted(cases_dir.iterdir()):
        if not case_dir.is_dir():
            continue
        if (case_dir / "AGENTS.md").is_file() or (case_dir / "CLAUDE.md").is_file():
            result.append(case_dir)
    return result


def _write_case_context_sync_reports(workbench_root: Path, report: ContextSyncReport) -> None:
    base = _render_context_sync_markdown(report).rstrip()
    for case_dir in _case_dirs_with_context_files(workbench_root):
        fp_dir = case_dir / ".framepack"
        fp_dir.mkdir(parents=True, exist_ok=True)
        case_report = (
            base
            + "\n## Case receipt\n"
            + "- scope: case\n"
            + f"- case_dir: {case_dir}\n"
        )
        (fp_dir / "context-sync.md").write_text(case_report, encoding="utf-8", newline="\n")


def hydrate_context(
    workbench_root: Path | str,
    plugin_dir: Path | str,
) -> ContextSyncReport:
    """Scan + update: sync managed blocks + strip stale bodies, then write report.

    Returns the final report (post-hydration).
    """
    workbench_root = Path(workbench_root)
    plugin_dir = Path(plugin_dir)

    # First: scan to know what needs updating
    initial = check_context_sync(workbench_root, plugin_dir)

    # Update files based on action needed
    for fs in initial.files:
        if not fs.exists or fs.action_needed == "none":
            continue
        try:
            if fs.action_needed == "replace_stale_body":
                # Strip old Framepack guide body, keep user content + managed block
                _strip_stale_body(Path(fs.path))
            elif fs.action_needed in ("append_block", "update_block"):
                sync_project_agents(Path(fs.path).parent, plugin_dir, ctx=None)
        except Exception:
            pass  # sync_project_agents handles its own errors

    # Write context-sync.md
    fp_dir = workbench_root / ".framepack"
    fp_dir.mkdir(parents=True, exist_ok=True)
    report_path = fp_dir / "context-sync.md"
    final = check_context_sync(workbench_root, plugin_dir)
    report_path.write_text(
        _render_context_sync_markdown(final), encoding="utf-8", newline="\n"
    )
    _write_case_context_sync_reports(workbench_root, final)

    return final


def _render_context_sync_markdown(report: ContextSyncReport) -> str:
    lines = [
        "# Framepack Context Sync",
        "",
        "## Source of truth",
        f"- version: {report.plugin_version}",
        f"- guardrails_hash: {report.plugin_digest}",
        "",
        "## Files checked",
        "| file | exists | managed_block | detected_version | stale | action |",
        "|---|---|---|---|---|---|",
    ]
    for fs in report.files:
        rel = fs.path
        if rel.startswith(report.workbench_root):
            rel = rel[len(report.workbench_root):].lstrip("\\/")
        lines.append(
            f"| {rel} | {fs.exists} | {fs.has_managed_block} | "
            f"{fs.detected_version} | {fs.is_stale} | {fs.action_needed} |"
        )
    lines.extend([
        "",
        "## Result",
        f"- project_context_current: {str(report.project_context_current).lower()}",
    ])
    if report.stale_files:
        lines.append(f"- stale_files: {len(report.stale_files)}")
        for s in report.stale_files:
            lines.append(f"  - {s}")
    else:
        lines.append("- stale_files: none")
    lines.append("")
    return "\n".join(lines)
