"""Gate artifact templates — placeholder structures for .framepack/ workflow files.

These templates are used by case_scaffolder.scaffold_case() and by
framepack-director skill when creating new workflow artifacts.

Each template is a string with clearly marked TODO sections.
"""

from __future__ import annotations

# Already defined inline in case_scaffolder.py PLACEHOLDER_BODY.
# This module exposes them as a stable import surface for skills and hooks.

DIRECTOR_INSPECT_TEMPLATE = """# Director Inspect

## Project intent
- video_type:
- audience:
- platform:
- duration:
- format:

## 9-question director rubric
1. Who is this for?
2. What must the first second make them feel?
3. What is the story turn?
4. What proof or concrete material makes it believable?
5. What assets are available?
6. What assets are missing but important?
7. Is music background, spine, or optional?
8. What must never appear?
9. What does success look like?

## Risk if we continue now
- missing_assets:
- likely_quality_ceiling:
- recommended_next_action:

## User decision
- provide_assets / generate_assets / continue_as_draft / waive
"""

SCRIPT_LANES_TEMPLATE = """# Script Lanes

## Lane A — Option One
- hook:
- beats:
- final line:
- why it fits:

## Lane B — Option Two
- hook:
- beats:
- final line:
- why it fits:

## Lane C — Option Three
- hook:
- beats:
- final line:
- why it fits:

## Selected lane
- lane:
- user_confirmed: false
- waiver_reason:
"""

ASSET_INTAKE_TEMPLATE = """# Asset Intake

## Brand
- logo:
  - path:
  - format:
  - transparent:
  - status:
- colors:
  - primary:
  - accent:
  - source:
- fonts:
  - heading:
  - body:
- slogan:

## Products

## Footage

## Text
- selling_points:
- cta:
- brand_story:

## Audio
- bgm:
- bgm_preference:
- voiceover:

## References

## Missing
"""

HANDOFF_MANIFEST_TEMPLATE = """# Handoff Manifest

- workflow:
- source_inputs:
  - url:
  - assets:
- creative_constraints:
  - tone:
  - metaphor:
  - rhythm:
  - forbidden:
- catalog_candidates:
- arsenal_candidates:
- qa_redlines:
- user_decision_points:
"""

CATALOG_DECISION_TEMPLATE = """# HyperFrames Catalog Decision

## Case needs
- lower thirds:
- kinetic title:
- data card:
- caption block:
- scene transition:

## Candidates evaluated
| candidate | use? | reason |
|---|---|---|

## Decision
- used_components:
- waived_components:
- reason_if_none_used:
"""

STUDIO_PREVIEW_TEMPLATE = """# Studio Preview Evidence

## Preview command
- command:
- started_at:
- URL:

## Inspection method
- browser / screenshot / snapshot / user live preview / skipped

## Observations

## Changes after preview
- changed:
- reason:

## Waiver
- skipped: false
- reason:
"""

SOURCE_INTAKE_TEMPLATE = """# Source Intake

## Source
- url:
- source_type: website / article / social / document / other
- extraction_method: web_extract / web_search / browser / manual / failed
- extraction_failed_reason:

## Extracted understanding
- source_summary:
- narrative_type:
- must_preserve_points:
  -
- claims_or_facts:
  -

## Director seed
- usable_angle:
- forbidden_misread:
- waiver_reason:
"""

DESIGN_CHOICE_TEMPLATE = """# Design Choice

## Ambiguity
- ambiguity_detected: false
- reason:

## Options presented
- options_presented:
  - name:
    mood:
    why_it_fits:

## Selection
- selected_style:
- selected_reason:
- picker_used: false
- user_confirmed: false
- waiver_reason:
"""

STORYBOARD_PREVIEW_TEMPLATE = """# Storyboard Preview

## Summary
- scene_count:
- user_confirmed: false
- waiver_reason:

## Recurring motifs
- recurring_motifs:
  -

## Scenes
### Scene 1
- Visual:
- Feel:
- Key:
- motif_state:
"""

RENDER_READINESS_TEMPLATE = """# Render Readiness Board

(generated by `python scripts/framepack_readiness.py <project>`)

| Gate | Status | Evidence | Risk |
|---|---|---|---|
"""

TASTE_AUDIT_TEMPLATE = """# Pre-render Taste Audit

## Checklist
- [ ] Director Story Bible match
- [ ] Depth layers present (BG + MG + FG)
- [ ] No stale source-domain props
- [ ] Rhythm matches user intent
- [ ] No placeholder-smell copy
- [ ] Assets are present where needed

## Findings

## Verdict
"""

ARSENAL_JSON_TEMPLATE = """{
  "weapons": {}
}
"""

CONTEXT_SYNC_TEMPLATE = """# Framepack Context Sync

(generated by `python scripts/framepack_scaffold_case.py --hydrate`)

## Source of truth
- version:
- guardrails_hash:
- synced_at:
"""

ALL_TEMPLATES = {
    "director-inspect.md": DIRECTOR_INSPECT_TEMPLATE,
    "script-lanes.md": SCRIPT_LANES_TEMPLATE,
    "asset-intake.md": ASSET_INTAKE_TEMPLATE,
    "handoff-manifest.md": HANDOFF_MANIFEST_TEMPLATE,
    "source-intake.md": SOURCE_INTAKE_TEMPLATE,
    "design-choice.md": DESIGN_CHOICE_TEMPLATE,
    "storyboard-preview.md": STORYBOARD_PREVIEW_TEMPLATE,
    "catalog-decision.md": CATALOG_DECISION_TEMPLATE,
    "studio-preview.md": STUDIO_PREVIEW_TEMPLATE,
    "render-readiness.md": RENDER_READINESS_TEMPLATE,
    "taste-audit.md": TASTE_AUDIT_TEMPLATE,
    "arsenal.json": ARSENAL_JSON_TEMPLATE,
    "context-sync.md": CONTEXT_SYNC_TEMPLATE,
}
