import type { CompositionScene, CompositionSpec } from "../types.js";

export function emitHyperframesComposition(spec: CompositionSpec) {
  const compositionId = "case-explainer";
  const html = [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="UTF-8" />',
    `  <meta name="viewport" content="width=${spec.width}, height=${spec.height}" />`,
    '  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>',
    "  <style>",
    "    * { margin: 0; padding: 0; box-sizing: border-box; }",
    `    html, body { width: ${spec.width}px; height: ${spec.height}px; overflow: hidden; background: #000; }`,
    "    .scene { position: absolute; inset: 0; display: grid; grid-template-columns: 1.05fr 0.95fr; gap: 56px; align-items: center; padding: 96px; color: #fff; opacity: 0; overflow: hidden; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }",
    "    .scene:first-child { opacity: 1; }",
    "    .scene-backdrop { position: absolute; inset: 0; z-index: -2; background: radial-gradient(circle at 20% 18%, rgba(84, 214, 255, 0.24), transparent 30%), linear-gradient(135deg, #07111f 0%, #101827 48%, #24122e 100%); }",
    "    .scene-problem .scene-backdrop { background: radial-gradient(circle at 18% 20%, rgba(255, 91, 91, 0.28), transparent 30%), linear-gradient(135deg, #180b13 0%, #211827 52%, #101827 100%); }",
    "    .scene-solution .scene-backdrop, .scene-workflow .scene-backdrop { background: radial-gradient(circle at 80% 22%, rgba(98, 255, 171, 0.25), transparent 30%), linear-gradient(135deg, #071a16 0%, #10232d 52%, #171b36 100%); }",
    "    .scene-ending .scene-backdrop { background: radial-gradient(circle at 50% 20%, rgba(255, 207, 87, 0.32), transparent 30%), linear-gradient(135deg, #111827 0%, #21123a 54%, #3a1025 100%); }",
    "    .scene-content { max-width: 1040px; }",
    "    .scene-kicker { display: inline-flex; margin-bottom: 28px; padding: 10px 16px; border: 1px solid rgba(255,255,255,0.24); border-radius: 999px; color: #9ee7ff; font-size: 26px; text-transform: uppercase; letter-spacing: 0; }",
    "    h1 { font-size: 86px; line-height: 0.98; letter-spacing: 0; max-width: 1000px; }",
    "    .scene-body { margin-top: 28px; color: #d7e5f4; font-size: 38px; line-height: 1.2; max-width: 900px; }",
    "    .scene-caption { margin-top: 34px; color: #91a3b8; font-size: 28px; line-height: 1.25; max-width: 900px; }",
    "    .scene-treatment { margin-top: 24px; color: #f7c95f; font-size: 24px; line-height: 1.25; max-width: 880px; }",
    "    .scene-hierarchy { margin-top: 12px; color: #7dd3fc; font-size: 20px; line-height: 1.2; max-width: 880px; text-transform: uppercase; letter-spacing: 0; }",
    "    .scene-asset-slot, .scene-asset-placeholder { min-height: 420px; border: 1px solid rgba(255,255,255,0.2); border-radius: 28px; background: rgba(255,255,255,0.08); box-shadow: 0 28px 90px rgba(0,0,0,0.28); display: flex; align-items: center; justify-content: center; overflow: hidden; }",
    "    .scene-asset-slot { flex-direction: column; }",
    "    .scene-asset-slot img { max-width: 100%; max-height: 360px; object-fit: contain; }",
    "    .scene-asset-slot figcaption, .scene-asset-placeholder { color: #b7c7d9; font-size: 24px; }",
    "    .scene-asset-slot figcaption { margin-top: 18px; }",
    "    @media (max-width: 1200px) { .scene { grid-template-columns: 1fr; padding: 64px; } h1 { font-size: 64px; } .scene-body { font-size: 30px; } }",
    "  </style>",
    "</head>",
    "<body>",
    `  <div id="stage" data-composition-id="${compositionId}" data-start="0" data-duration="${spec.durationSec}" data-width="${spec.width}" data-height="${spec.height}" data-palette="${spec.theme.palette}">`,
    ...spec.scenes.map((scene: CompositionScene) => `    ${scene.htmlTemplate}`),
    "  </div>",
    "  <script>",
    "    window.__timelines = window.__timelines || {};",
    "    const tl = gsap.timeline({ paused: true });",
    "    gsap.set('.scene', { opacity: 0 });",
    "    document.querySelectorAll('.scene').forEach((scene, index) => {",
    "      tl.to(scene, { opacity: 1, duration: 0.45, ease: 'power2.out' }, index * 10);",
    "      tl.fromTo(scene.querySelector('.scene-content'), { y: 34, opacity: 0 }, { y: 0, opacity: 1, duration: 0.7, ease: 'power3.out' }, index * 10 + 0.1);",
    "      tl.fromTo(scene.querySelector('.scene-asset-slot, .scene-asset-placeholder'), { scale: 0.96, opacity: 0 }, { scale: 1, opacity: 1, duration: 0.75, ease: 'power3.out' }, index * 10 + 0.25);",
    "      tl.to(scene, { opacity: 0, duration: 0.35, ease: 'power2.in' }, index * 10 + 9.4);",
    "    });",
    `    window.__timelines["${compositionId}"] = tl;`,
    "  </script>",
    "</body>",
    "</html>",
  ].join("\n");

  return {
    html,
    commands: {
      preview: "npx hyperframes preview",
      lint: "npx hyperframes lint",
      validate: "npx hyperframes validate",
      render: "npx hyperframes render",
    },
  };
}
